language: elixir
elixir:
  - 1.1.1
  - 1.2.6
  - 1.3.0
  - 1.3.4
  - 1.4.0
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
otp_release:
  - 18.1
script:
  - "MIX_ENV=test mix do deps.get, compile, coveralls.travis"
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report

branches:
  only:
  - master
  - travis